---
- hosts: all
  become: true
  tasks:
  - name: building docker image
    command: docker build -t helloworldshankar .
    args:
      chdir: /opt/ansible
  - name: tag docker image
    command: "docker tag helloworldshankar vijayakrishnajava/helloworldshankar:latest"
  - name: auth
    command: "docker login -u={{user}} -p={{pass}}"
  - name: push the name to registry
    command: docker push vijayakrishnajava/helloworldshankar:latest
  - name: cleaning
    command: docker system prune -f -a
  
        
